version: "3.8"
services:
  wordpress:
    image: wordpress
    container_name: "wordpress-1"
    ports:
      - "8085:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "admin"
      WORDPRESS_DB_NAME: wordpress
  wordpress-1:
    image: wordpress
    container_name: "wordpress-2"
    ports:
      - "8086:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "admin"
      WORDPRESS_DB_NAME: wordpress
  wordpress-2:
    image: wordpress
    container_name: "wordpress-3"
    ports:
      - "8087:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "admin"
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: "mysql:5.7"
    container_name: "mysql-db"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - ./mysql:/var/lib/mysql
